### ISSUE TITLE
Is this still functional?

### ISSUE THREAD

**Issue by interdrift** [DarkAutumn/TwitchLib#1]
I have tried using it but it appears that it isn't functioning for the current state of Twitch?

**Comment by DarkAutumn** [comment]
Try the one in the WinterBot project, which I think is more up to date than
that one.  There's other stuff in that project than just the twitch
library, but it has a full working copy as of the last time I used it:
https://github.com/DarkAutumn/WinterBot/tree/master/WinterBot

However, I haven't touched the project in almost a year.  It's possible
twitch made changes so that it needs updating, but I've lost interest in
the project.  I won't be making updates myself.
